---
name: Sebastian
surname: Bate
position: "Medical Statistician"
phone: 07985357150
#www: 
email: "sebastiangbate@gmail.com"
twitter: sebastianbate
github: sgbstats
linkedin: sebastianbate
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Experience

```{r}
tribble(
  ~Org, ~Role,~Time,  ~Responsibilities,
  "Manchester University NHS Foundation Trust", "Junior Medical Statisitican", "Mar 2021-", list("I have been involved in multiple studies and lead on statistical design and analysis from concept through to dissemination.","I support all levels of researchers from undergraduate and postgraduate students, through to clinical academics and consultants.","I have been responsible for reviewing the design, statistical accuracy and overall viability of all trust sponsored research protocols prior to ethics submission in collaboration with senior statisticians","I have multiple collaborations with clinicians across the whole of MFT, The University of Manchester, and other trusts, including Renal, Critical Care, Gastroenterology, Cardiovascular, Cystic Fibrosis, Respiratory, Oncogeriatrics, Dermatology, Oncoplastic Surgery, Physiotherapy, Maternity, Trauma Care, and ENT.", "I am the resident statistician for Respiritory Medicine Journal Club where I lead discussions critically appraising research and providing statistical context", "I have given multiple talks on statistics for critical appraisal accross the trust and I am the subject matter expert for meta-analysis.", "I have provided informal mentoring to junior team members"),
  
  "IQVIA", "Statistician", "Sep 2019-Feb 2021", list("I worked with senior biostatistics staff on the evaluation, interpretation, and reporting of study results, including writing the analysis data reviewer’s guide for one study.","I quality controlled regulatory documents including CSRs, summaries of clinical efficacy and safety, prescribing information, and FDA briefing documents for large pivotal studies.","I assisted in developing study analysis plans, including sample size calculations, and mock TFLs across multiple studies.", "I programmed TFLs for use in CSRs across multiple studies.", "I provided guidance and interpretation on statistical matters to medical writers and statistical programmers.","I gained experience in applying the principles in ICH E6 (GCP), E9 (Statistics), E9R1 (Estimands).")
) %>% 
  detailed_entries(what=Role, where = Time, with = Org, why=Responsibilities)

```

# Education

```{r}

tribble(
  ~ Degree, ~ Year,~Grade, ~ Institution, 
  "MMath Mathematics and Statisitcs", "2015-19", "First Class (Hons.)", "University of Manchester"
) %>% 
  detailed_entries(why=Grade,where=Year,with=Degree,  what=Institution)
```


# Publications

```{r}
library(dplyr)
#knitr::write_bib("bib.bib")

bibliography_entries("bib.bib") %>%
  arrange(desc(issued))
```
# Grants Awarded

```{r}
tribble(
  ~Body, ~Title, ~Year, ~Detail, ~Where,
  "Wellcome Trust Institutional Translational Partnership Award Access to Expertise",
 "Prediction Tools to personalise medicine in ANCA-associated vasculitis. ",
 "2021",
 list("Brix, S et al., £4,760", "Role: Junior Statistician"),
  "University of Manchester"
) %>% 
  detailed_entries(with=Body, what=Title, where=Year, why=Detail, when=Where)
```
# Languages & Certifications
* R, inc. Tidyverse (Expert)
* SPSS (Proficient)
* SAS (Was proficient, now rusty)
* SQL (Moderate)
* NIHR Good Clinical Practice


# Personal
* I have run a 3:28:52 marathon
* This CV was written in RMarkdown using {vitae}

